### ISSUE TITLE
Officially cut over to new Vector helm charts

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10004]
This issue comprises the remaining work to cut over to the new chart and deprecate the old charts.

Tasks:

- [x] #10467
- [x] Update documentation to refer to new `helm-charts/vector` chart (remove Beta note)
  - [x] https://github.com/vectordotdev/vector/issues/8485
- [x] #10595
- [x] https://github.com/vectordotdev/vector/issues/8714
- [x] #10656
- [x] https://github.com/vectordotdev/vector/pull/9745

**Comment by spencergilbert** [comment]
#10656 blocked pending approval of #10595

**Comment by jszwedko** [comment]
@spencergilbert are there are more tasks to be done here? I noticed the above are all checked.

**Comment by spencergilbert** [comment]
Ah no, I forgot to add it to the last pr. Will close!

**Comment by jszwedko** [comment]
🥳
