### ISSUE TITLE
`kubernetes_logs` source fixes

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10016]
This epic represents the work we are doing this quarter to improve the `kubernetes_logs` source.

- [ ] https://github.com/vectordotdev/vector/issues/7527 (we could skip the RFC if we think the scope is limited; we just really need to address https://github.com/vectordotdev/vector/issues/8616)
- [ ] https://github.com/vectordotdev/vector/issues/8616
- [x] https://github.com/vectordotdev/vector/issues/8345
- [x] https://github.com/vectordotdev/vector/issues/7943

**Comment by spencergilbert** [comment]
We're expecting we'll have a number of issues resolved by https://github.com/vectordotdev/vector/pull/11714 and can tackle issues that come up with the source rewrite more easily.
