### ISSUE TITLE
Prepare 0.18.0 release

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#10019]
* [x] Highlight failed events routing @barieom #10052 
* [x] Highlight CSV enrichment @barieom #10041 
* [x] Survey which additional event processing metrics are emitted and document all in a highlight @jszwedko 
* [x] Highlight added buffer instrumentation @jszwedko 
* [x] Highlight `throttle` transform #10015  @barieom 
* [x] Highlight implicit directory namespacing @barieom #10048 
* [x] ~Highlight new `pipelines` transform @barieom~
* [x] Check with Luke about transform utilization improvements @jszwedko 
* [x] Call out new Helm chart release @jszwedko 
* [x] https://github.com/vectordotdev/vector/issues/9983 @jszwedko  https://github.com/vectordotdev/vector/pull/10039
* [x] Write release notes @jszwedko

**Comment by jszwedko** [comment]
This was released.
