### ISSUE TITLE
Soak Test Improvements

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#10445]
Now that we've sat with the soak tests for a spell it's clear there are some quality of life and functionality extension changes we can make. These are: 

# Must Have

* [x] #10497
* [x] #10400
* [x] #10606
* [x] #10931
* [x] #10626
* [ ] #10447
* [x] #11772
* [ ] #11971
* [x] #12428
* [ ] #12444

# Nice To Have

* [ ] #10800
* [ ] #10454
* [ ] https://github.com/vectordotdev/vector/issues/10777
* [ ] #10493
* [ ] #10446
* [ ] #11152
* [ ] https://github.com/vectordotdev/vector/issues/12186

# Would Be Cool

* [ ] #10455
* [ ] #10456
* [x] #9543
* [ ] https://github.com/blt/lading/issues/130
* [ ] #10562
* [ ] #10494
* [x] https://github.com/vectordotdev/vector/issues/10637

**Comment by jszwedko** [comment]
Closing since this epic was completed. The rest of the work was deferred and tracked separately.
