### ISSUE TITLE
Implement end-to-end record acknowledgement

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#1107]
## Summary

There does not appear to be any communication of acknowledgements from sinks to their source(s). This could cause dropped records if Vector is interrupted (killed) between receiving a record from a source and fully communicating it to the corresponding sink(s), which in turn voids the "at least once" delivery guarantee listed in most of the sinks.

For sources that record state checkpoints, this may be avoided by communicating acknowledgements upstream, and only marking records as read after they have been acknowledged by the sinks.

- docker source explicitly only looks at records starting at Vector start time, so no changes required
- file source stores checkpoints for each opened file to avoid re-reading
- journald source stores a checkpoint after each read batch
- kafka source acknowledges each message as soon as they are read, which is committed every 5 seconds by default (if I'm reading it right)
- The stdin, syslog, tcp, udp, and vector sources have no backing store, and no protocol support for acknowledgements, so cannot save any state.

This is of course complicated by the fact that each source may have multiple sinks (and each each sink may be receiving from multiple sources) and that the data may be passing through transforms that may drop records.

## Jobs to be done
- When using Vector with otherwise high-reliability components, Vector should match those existing guarantees and not be a weak link in the overall system
- When a customer asks about reliability or delivery guarantees, we need to provide a simple and satisfactory answer so that they can feel confident adopting Vector

## Requirements
- [ ] Acknowledgments to sources like Kafka should be precise and only include events Vector has finished processing
- [ ] Sources like the file source that manage checkpoints internally should only save those for which it does not need to reread on restart (similar to Kafka above)
- [ ] For sources like HTTP, Vector should have the ability (but not the requirement) to defer responding 200 OK until it has finished processing the incoming events
- [ ] Acknowledgements must be flexible and configurable, accounting for use cases with multiple sinks, disk buffers, etc without forcing users down a single path
- [ ] Clear, understandable documentation around delivery guarantees in various scenarios

## Out of scope
- This is an attempt to better match the semantics of some of the existing systems we integrate with, not to try to add the idea of acknowledgement to sources that do not natively support it (e.g. sockets, syslog, etc)

**Comment by binarylogic** [comment]
Thanks, @bruceg, this is a nice write up. This is a known issue that we've discussed a number of times internally. I actually have a project on our roadmap to address this in January. That said, I am of the mindset that if a user configures on-disk buffers we can offer an at least once guarantee. Let me know if this is not correct.

**Comment by bruceg** [comment]
Thanks for the confirmation, it's good to know I wasn't totally misreading on this point.

Re buffers, my understanding is that they are configured into each sink, which means that records are written into the buffer after they would be acknowledged in the source. So, there is still a gap (admittedly a small race) between acknowledgement and buffering, particularly if any errors are encountered while writing the buffer.

**Comment by anton-ryzhov** [comment]
Another downside of this architecture — enabling buffers for sources with checkpoints increases IO.
With `file` source `vector` reads files and writes this data back on disk — much easier will be to not commit new offsets.

For some cases local buffers could be useful (if source's buffer is small). But if we can rely on that buffer — it's better to not have another buffer.

**Comment by jszwedko** [comment]
Just surfacing that this has come up in gitter a couple of times, latest: https://gitter.im/timberio-vector/community?at=5f3e061c5d0f8f2440813f98 . I'll try to link here as it comes up again.

I think Bruce's note that even the disk buffer doesn't completely mitigate the risk of dropping messages is prescient. We'd need to wait to ACK the source until it was written to disk (and maybe flushed?).

@binarylogic In my opinion, this is a "have: must". Without it (or at least flushing to disk before ACKing), I don't think we can guarantee "at least once" delivery.

**Comment by bruceg** [comment]
Now that I'm a little more familiar with the code base (and a little less naïve, I hope), it's worth asking if we really want full end-to-end acknowledgements, or if source-to-stored is what we're after. By that I mean that the source events have been stored somewhere such that they *will be delivered* at some point in the future even if vector crashes. In this model, a persistent buffer (ie disk) would be able to provide such an acknowledgement well before the events are even started to be delivered. This would provide for the at-least-once semantics we desire without incurring the cost of the full latency when acknowledging incoming data.

This effectively divides our acknowledgement pipeline into two parts: source-to-buffer and buffer-to-sink. The latter is, of course, already covered by the current sink framework with its explicit `Acker`. I propose to add a similar acker to the pipelines between the sources and buffer that would provide that feedback when the (transformed) events are stored durably for delivery.

**Comment by jszwedko** [comment]
Closing this as the initial work was done and the follow-up work is captured by https://github.com/vectordotdev/vector/issues/9877
