### ISSUE TITLE
Test new VRL enum VM

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11195]
- [x] Add the fuzz test project to run both VRL implementations and compare the results.
- [x] Implement `Arbitrary` for the VRL Ast to generate useful programs given random input. (60% complete)
- [x] Update the `test_function` macro so it tests both the current VRL stdlib functions and the VM stdlib implementation.
- [x] Add `criterion` benchmarks to compare the performance of both VRL implementations.
