### ISSUE TITLE
Internal Event Schema Support

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#11300]
Tracking issue for the ongoing work related to internal event schema support.

[**product brief**](https://docs.google.com/document/d/1BmtX5VaDmzSVlf3Pys8tLN8cJpZXj21bJSwMnWzIg00/edit?usp=sharing)

Work to be done:

- [x] https://github.com/vectordotdev/vector/pull/10906
- [x] https://github.com/vectordotdev/vector/pull/11296
- [x] https://github.com/vectordotdev/vector/pull/11268
- [ ] https://github.com/vectordotdev/vector/pull/11277
- [ ] Add schema definition to Datadog Agent source
- [ ] Add support for custom TypeDef passed to VRL compiler
- [ ] Hook up topology to pass schema definitions to VRL compiler, with global option turned off by default
- [ ] Update VRL to support more than one external data source
- [ ] * Change VRL to support compile-time-only functions, needed for semantic meaning functions
- [ ] Add semantic meaning functions that change definition passing through remap transform
- [ ] * Update encoding formats to support schema requirements
- [ ] Add schema requirement to Datadog Log sink
- [ ] * Hook up schema requirements to topology, preventing vector from booting if needed, hide behind new disabled by default global option
