### ISSUE TITLE
Google Chronicle Sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#11532]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Users would like to send data to Google Chronicle via Vector.

### Attempted Solutions

Using a custom `reduce` transform to create the payload expected by Google Chronicle and then using the `http` sink with batch size 1 to send the already batched event.

### Proposal

A new sink for Google Chronicle.

### Version

0.22.0

### Subtasks

- [ ] [RFC](https://github.com/vectordotdev/vector/pull/12733)
- [ ] Send unstructured events to Google Chronicle
  - [x] #16368
- [ ] #16369
  - [ ] Integration testing
- [ ] Add schema support for UDM events to Google Chronicle

**Comment by spencergilbert** [comment]
https://cloud.google.com/chronicle/docs/unified-data-model/format-events-as-udm
https://cloud.google.com/chronicle/docs/reference/ingestion-api#ingestion_api_reference

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/13550 though it only supports unstructured data. I split off UDM into https://github.com/vectordotdev/vector/issues/16369
