### ISSUE TITLE
Integrate `codecs::Encoder` with `http` sink

### ISSUE THREAD

**Issue by pablosichert** [vectordotdev/vector#11579]
The integration encompasses the following tasks :
- [x] Implement encoding support structures: #10253
- [x] Implement adapter from old encoding options to new encoders: #10253
- [x] Make all options of encoders known to be able to infer HTTP content type header: #11194
- [x] Refactor `HttpSink` related code to operate on `BytesMut` rather than `Vec<u8>` for integration with `tokio_util::codecs::Encoder`: #11232
- [ ] Refactor `HttpSink` to allow using `&mut self` in `encode_event` by creating a new `Encoder` for every HTTP request
- [ ] Integrate new encoding options with `http` sink
