### ISSUE TITLE
Adopt more opinionated schema for logs

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12187]
When implementing Vector's new internal schema as part of https://github.com/vectordotdev/vector/issues/11300 we ran into a rough edge due to the fact that fields decoded by codecs take precedence over source metadata fields, making it impossible to have a defined schema when a dynamic codec like `json` is used.

We'd like to start nesting dynamic fields to avoid conflicts. For example, the [OpenTelemetry schema](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md) does this with its `Attributes` and `Body` fields.

We'd like this modified log event schema to be opt-in, at first, to migrate users over to it, eventually deprecating the current schema.

# Requirements

See [RFC](https://github.com/vectordotdev/vector/blob/master/rfcs/2022-04-20-12187-log-namespacing.md) for details.

- Events can be any value rather than just maps
  - If sinks need structured data, and the event is not a map, than the root is mapped into a `message` key (hardcoded)
- `log_namespace` configuration option exists at the source and global level that accepts a boolean. `true` opts into the new namespacing schema.
- `log_schema` options are ignored when `log_namespace` is `true` for a given event (or global)
- When `log_namespace` is true, there are three components to an event: the event data, event metadata, secrets
  - The event data are just the decoded data and not any additional metadata added by sources
  - Source metadata is added to event metadata rather than the event data
  - Secrets are moved to new event secrets storage rather than event metadata
- Datadog API key and Splunk HEC token that were in event metadata are now in event secrets, but can be accessed via `get_metadata_field` for compatibility
- `get_secret`, `set_secret`, `remove_secret` exist for retrieving, setting, and removing data from event secrets. This is just string -> string key/value.
- `get_metadata_field` can query arbitrary paths and return arbitrary value types (rather than just strings)
- `set_metadata_field` allows setting arbitrary data (like `.`)
- `remove_metadata_field` allows removing arbitrary paths (like `.`)
- `get_metadata_field` is backwards compatible with existing secrets (including typing as string)
- Vector added metadata is added to event metadata under `vector` key: `source_type`, `ingest_timestamp`

# Subtasks
- [x] https://github.com/vectordotdev/vector/pull/12665
- [x] https://github.com/vectordotdev/vector/pull/12705
- [x] https://github.com/vectordotdev/vector/pull/12767
- [x] https://github.com/vectordotdev/vector/pull/12218

More will be added for other components.

# Future enhancements

- Add a special path syntax to reference metadata (and secrets) instead of using functions.
- Expand schema support to metadata
- Expand semantic meaning to metadata
- Allow sources to be configured to pull in additional data into the event (from the metadata)
- Allow sinks to be configured to pull in additional data from metadata
- Persist metadata in disk buffers. Sinks will require metadata to be able to differentiate between namespaces.

**Comment by jszwedko** [comment]
I talked with @fuchsnj about this today. He's going to open a PR against the `datadog_agent` source to implement this as a proof-of-concept to let us discuss how we want to implement this for all sources.

**Comment by jeromekleinen-kbc** [comment]
Personally the first thing I end up doing in many of my configs is to drop the metadata added by the source, and indeed the overlap between the metadata field names and the field names from my actual data is rather annoying.

It might be interesting to have a configuration option, either globally or on source level, which defines the key name for all the metadata. I can think of two possible structures:

#### Only separate out the metadata

```javascript
{ "vector_metadata": { "source_type": "xxx", "topic": "yyy"}, "log_field1": "value1", "log_field2": "value2"}
```

This could be easily combined with the except_fields settings

#### Split event data and metadata at the first level
```javascript
{ "vector_metadata": { "source_type": "xxx", "topic": "yyy"}, "event_data": { "log_field1": "value1", "log_field2": "value2"}}
```

In the latter case could be easily combined with the only_fields setting, but ideally I would want an option to remove the "event_data" key name above the actual fields.

**Comment by jszwedko** [comment]
Thanks for the thoughts @jeromekleinen-kbc ! We are leaning towards the second option you have there (key names TBD).

**Comment by jszwedko** [comment]
Closing since this was released as beta in v0.31.0.
