### ISSUE TITLE
Adhere components to instrumentation spec

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#12921]
This is a meta issue that supersedes #11991, #9688, #9687, and #9325.

Vector's internal observability is critical, not only to provide users with rich insight in how Vector is behaving, but to also drive our enterprise product. Up to this point adherence to the [instrumentation specs](https://github.com/vectordotdev/vector/tree/master/docs/specs) has been shoddy. Some components were not instrumented at all and others were instrumented incorrectly. #12668, #12572, and #12755 aimed to bring all of the components into adherence by simply checking that each component emits the proper events, but it does not check correctness (i.e., that `component_received_bytes_total` is accurate based on specific input). In addition, the spec is changing while we get more clarity on the enterprise product requirements (i.e., #12912, #12892, #12822). Therefore, we need a solid plan that lays a strong foundation for instrumentation and drives correct implementation regardless of who's implementing it.

### Foundation

- [X] Ensure all sources emit the proper events with unit tests (#12572)
- [X] Ensure all transforms emit the proper events with unit tests (#12668)
- [X] Ensure all sinks emit the proper events with unit tests (#12755)
- [ ] Ensure instrumentation correctness for the `aws_s3_source` source
- [ ] Ensure instrumentation correctness for the `route` transform
- [ ] Ensure instrumentation correctness for the `datadog_metrics` sink

### Adherence

Adherence is blocked on the foundational issues above.

#### Sources

- [ ] Ensure instrumentation correctness for the ... source

#### Transforms

- [ ] Ensure instrumentation correctness for the ... transform

#### Sinks

- [ ] Ensure instrumentation correctness for the ... sinks
