### ISSUE TITLE
Audit of sources and sinks

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#13740]
We are doing a refresh of our sources and sinks.

For each component:

- [ ] Refresh configuration documentation: ensure it is accurate and proofread
- [ ] Update examples to be real-world
- [ ] Update [component status](https://vector.dev/docs/about/under-the-hood/guarantees/#stability-guarantees) (beta or stable)
- [ ] Ensure `vector generate` generates a valid configuration
- [ ] Verify internal event processing metrics are tested via `assert_X_compliance` test helpers
- [ ] Update `component_discarded_events_total` to match the new [instrumentation spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md#eventsdropped) by adding `reason` to the emitted logs, and `intentional` to emitted logs and metrics
- [ ] Add source level type definitions and log namespacing support (example PR for `demo_logs` source: https://github.com/vectordotdev/vector/pull/13720)
- [ ] Document any deprecated metrics on the website
- [ ] For sinks, add a warning to old-style sinks to avoid contributors using them to bootstrap new sinks
- [ ] For sinks, relax allowed input types where possible to match codec support

Copy this checklist when creating the issue for each component.

Sources:

@spencergilbert 

- [ ] Audit `aws_ecs_metrics` source
- [ ] Audit `aws_kinesis_firehose` source
- [ ] Audit `aws_s3` source
- [ ] Audit `aws_sqs` source
- [ ] Audit `logstash` source
- [ ] Audit `mongodb_metrics` source
- [ ] Audit `nats` source
- [ ] Audit `nginx_metrics` source
- [ ] Audit `opentelemetry` source

@neuronull 

- [ ] Audit `datadog_agent` source
- [ ] Audit `apache_metrics` source
- [ ] Audit `host_metrics` source
- [ ] Audit `http` source
- [ ] Audit `internal_logs` source
- [ ] Audit `internal_metrics` source
- [ ] Audit `journald` source
- [ ] Audit `file` source
- [ ] Audit `kubernetes_logs` source

@StephenWakely 

- [ ] Audit `gcp_pubsub` source
- [ ] Audit `demo_logs` source
- [ ] Audit `dnstap` source
- [ ] Audit `docker_logs` source
- [ ] Audit `eventstoredb_metrics` source
- [ ] Audit `exec` source
- [ ] Audit `fluent` source
- [ ] Audit `heroku_logs` source
- [ ] Audit `kafka` source

@prognant 

- [ ] Audit `postgresql_metrics` source
- [ ] Audit `prometheus_remote_write` source
- [ ] Audit `prometheus_scrape` source
- [ ] Audit `redis` source
- [ ] Audit `socket` source
- [ ] Audit `splunk_hec` source
- [ ] Audit `statsd` source
- [ ] Audit `stdin` source
- [ ] Audit `syslog` source
- [ ] Audit `vector` source

Sinks:

@spencergilbert 

- [ ] Audit `aws_cloudwatch_logs` sink
- [ ] Audit `aws_cloudwatch_metrics` sink
- [ ] Audit `aws_kinesis_firehose` sink
- [ ] Audit `aws_kinesis_streams` sink
- [ ] Audit `aws_s3` sink
- [ ] Audit `aws_sqs` sink
- [ ] Audit `axiom` sink
- [ ] Audit `logdna` sink
- [ ] Audit `loki` sink
- [ ] Audit `nats` sink
- [ ] Audit `new_relic` sink
- [ ] Audit `new_relic_logs` sink

@StephenWakely 

- [ ] Audit `azure_blob` sink
- [ ] Audit `azure_monitor_logs` sink
- [ ] Audit `blackhole` sink
- [ ] Audit `chronicle_unstructured` sink
- [ ] Audit `clickhouse` sink
- [ ] Audit `console` sink
- [ ] Audit `elasticsearch` sink
- [ ] Audit `gcp_cloud_storage` sink
- [ ] Audit `gcp_pubsub` sink
- [ ] Audit `gcp_stackdriver_logs` sink
- [ ] Audit `gcp_stackdriver_metrics` sink
- [ ] Audit `honeycomb` sink

@neuronull 

- [ ] Audit `datadog_archives` sink
- [ ] Audit `datadog_events` sink
- [ ] Audit `datadog_logs` sink
- [ ] Audit `datadog_metrics` sink
- [ ] Audit `datadog_traces` sink
- [ ] Audit `file` sink
- [ ] Audit `http` sink
- [ ] Audit `humio_logs` sink
- [ ] Audit `humio_metrics` sink
- [ ] Audit `influxdb_logs` sink
- [ ] Audit `influxdb_metrics` sink
- [ ] Audit `kafka` sink

@prognant 

- [ ] Audit `papertrail` sink
- [ ] Audit `prometheus_exporter` sink
- [ ] Audit `prometheus_remote_write` sink
- [ ] Audit `pulsar` sink
- [ ] Audit `redis` sink
- [ ] Audit `sematext_logs` sink
- [ ] Audit `sematext_metrics` sink
- [ ] Audit `socket` sink
- [ ] Audit `splunk_hec_logs` sink
- [ ] Audit `splunk_hec_metrics` sink
- [ ] Audit `statsd` sink
- [ ] Audit `vector` sink
- [ ] Audit `websocket` sink
