### ISSUE TITLE
VRL Playground

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#14652]
This is a tracking issue for the "VRL Playground" feature @jonathanpv is working on.

**Project Name**

VRL Playground

**Project Summary**

A website that functions similar to the VRL REPL, in that it allows users to try out their VRL programs in real-time, before applying it to a Vector configuration.

**Background**

VRL (Vector Remap Language) is the domain-specific language used in Vector to programmatically remap events, or apply conditional transforms. It is intended as a safe and easy-to-use language that is performant enough to handle high-throughput use-cases.

**Goals**

_essential goals_

- [ ] Compile VRL to WASM (target: `wasm32-unknown-unknown`)
- [ ] Compile compatible VRL standard library functions to WASM
- [ ] Expand VRL test harness to allow running tests in WASM environment
- [ ] Embed VRL in webpage and run it through browser console
- [ ] Add MVP web UI to run VRL program without access to browser console
- [ ] Display VRL diagnostic messages in web UI

_desired goals_

- [ ] Provide "share" feature to share exact copy webpage with others
- [ ] Allow running VRL program against multiple log events
- [ ] Expand web UI design beyond MVP status, using Vector's website style guide

_stretch goals_

- [ ] Add syntax highlighting
- [ ] Add keyboard shortcut support
- [ ] Add advanced IDE features (auto-completion, inline docs, etc...)
- [ ] Add button to convert tested program to working Vector `config.toml` file
- [ ] Expand `vector vrl` CLI to run playground locally (`vector vrl playground`)
- [ ] Support multiple VRL (Vector) versions
