### ISSUE TITLE
Support duplicate tag and bare tags on metrics

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#14742]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

https://github.com/vectordotdev/vector/issues/14707#issuecomment-1268873637 gave an example of the Datadog Agent sending a metric that has duplicate tag keys for `kube_service`. Vector, however, uses a key/value map for tags and so can only store one of those values.

Example:

```json
              {
                "host": "<instance-id>",
                "interval": 0,
                "metric": "kubernetes.containers.running",
                "points": [
                        [
                                1664997945,
                                1
                        ]
                ],
                "source_type_name": "System",
                "tags": [
                        "clusterid:<redacted>",
                        "docker_image:<redact>.dkr.ecr.us-west-2.amazonaws.com/<redact>",
                        "image_id:docker-pullable://<redact>.dkr.ecr.us-west-2.amazonaws.com/<redact>",
                        "image_name:<redact>.dkr.ecr.us-west-2.amazonaws.com/<redact>",
                        "image_tag:<redacted>",
                        "kube_container_name:<redacted-service-name-that-disappears>",
                        "kube_namespace:<redacted-just-the-k8-namespace>",
                        "kube_ownerref_kind:statefulset",
                        "kube_qos:Burstable",
                        "kube_service:<redact>",
                        "kube_service:<redact>-0-internal",
                        "kube_service:<redact>-discovery",
                        "kube_stateful_set:<redact>",
                        "persistentvolumeclaim:data0-<redact>-0",
                        "pod-name:<redact>-0",
                        "pod_phase:running",
                        "short_image:<redact>"
                ],
                "type": "gauge"
        }

```

Ideally Vector could support a more flexible tag model which allows for duplicate keys. It should also support keys with no associated value.

A cross-cutting concern is that sinks may have varying support for these sorts of tags.

RFC: https://github.com/vectordotdev/vector/pull/14838

### Tasks

- [X] #14835 
- [x] #14984
- [x] #15177
- [x] #15182
- [x] #15344 
- [x] #15286
- [x] #15309 
- [x] #15402
- [x] #15272
- [x] #15419 
- [x] Audit all uses of `MetricTags::replace` to see if they should use `insert`.
- [x] #15420
- [x] #15343
- [x] #15423 
- [x] #15425
- [x] #15505
- [x] #15721 

Next steps:

- [ ] Add deprecation warnings for single-valued tags behavior (Lua and VRL)
- [ ] Change default behavior to multi-valued tags (Lua and VRL)
- [ ] Drop single-valued tags support (Lua and VRL)
- [ ] Add compile-time checking to VRL for metric field assignments (specifically tags)

**Comment by jszwedko** [comment]
> Is it possible for the same tag to have both multiple values _and_ bare tags? That will help inform the data structure we choose to use internally.

For posterity, I believe yes.
