### ISSUE TITLE
Update data volume metrics to use estimated JSON size

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#14801]
Requirements:

- [ ] Sources emit `component_received_event_bytes_total` that corresponds to the estimated JSON size of received events
- [ ] Sources emit `component_sent_event_bytes_total` that corresponds to the estimated JSON size of sent events
- [ ] Transforms emit `component_received_event_bytes_total` that corresponds to the estimated JSON size of received events
- [ ] Transforms emit `component_sent_event_bytes_total` that corresponds to the estimated JSON size of sent events
- [ ] Sinks emit `component_received_event_bytes_total` that corresponds to the estimated JSON size of received events
- [ ] Sinks emit `component_sent_event_bytes_total` that corresponds to the estimated JSON size of sent events
- [ ] `vector top` shows these bytes as input/output for each component

Metric tags should match description in [component spec](component spec).

Ref: https://github.com/vectordotdev/vector/pull/14139
