### ISSUE TITLE
Tracking Issue: Log Namespacing Support

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#15003]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Requirements

- [x] All sources need to be modified to support log namespacing. This includes configuration for the namespace, adjusting the event format, and changing the type definition. [Add support to all sources](https://github.com/vectordotdev/vector/issues/13723)
- [x] Transforms need to be audited / adjusted as needed. Transforms that don't work on logs can be skipped. There are some edge cases such as the remap transform adding error details to the event which change with the new namespace. Type definitions will need to be added / updated to support the new namespaces. Any reference to the "global log schema" needs to be removed when using the new namespace. [Add support to all transforms](https://github.com/vectordotdev/vector/issues/15031)
- [x] Sinks need to be audited / any reference to the "global log schema" needs to be removed when using the new namespace. [Add support to all sinks](https://github.com/vectordotdev/vector/issues/15453)
- [x] https://github.com/vectordotdev/vector/issues/17193
- [x] Document new log namespace feature in reference documentation (https://github.com/vectordotdev/vector/pull/16571)
- [x] Write up blog post announcing feature (https://github.com/vectordotdev/vector/pull/16571)

### Optional / nice to have
- [x] Make the schema requirement non-optional / enforced by the Rust type system. (Currently it's optional since it's not implemented for all components yet, but that will be completed as part of this work). This will make sure schema definitions can't be accidentally left out for new sources/transforms.
