### ISSUE TITLE
Tracking issue: Add Log Namespace support to transforms

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#15031]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Tracking issue for all the Log Namespacing work: https://github.com/vectordotdev/vector/issues/15003

Transforms need to be audited / adjusted as needed. Transforms that don't work on logs can be skipped. There are some edge cases such as the remap transform adding error details to the event which change with the new namespace. Type definitions will need to be added / updated to support the new namespaces. Any reference to the "global log schema" needs to be removed when using the new namespace.

### Transforms (in no particular order)

- [x] https://github.com/vectordotdev/vector/pull/15032
- [x] pipelines (this delegates to other components, so there is nothing to do here)
- [x] https://github.com/vectordotdev/vector/pull/15198
- [x] aggregate (metrics only, no changes needed)
- [x] https://github.com/vectordotdev/vector/pull/15107
- [x] https://github.com/vectordotdev/vector/pull/15089
- [x] https://github.com/vectordotdev/vector/pull/15036
- [x] https://github.com/vectordotdev/vector/pull/15090
- [x] https://github.com/vectordotdev/vector/pull/15526
- [x] https://github.com/vectordotdev/vector/pull/15144
- [x] remap transform: https://github.com/vectordotdev/vector/pull/12218
- [x] https://github.com/vectordotdev/vector/pull/15035
- [x] https://github.com/vectordotdev/vector/pull/15034
- [x] tag_cardinality_limit (only metrics are supported, nothing to do here)
- [x] https://github.com/vectordotdev/vector/pull/15033
