### ISSUE TITLE
Tracking issue: Add Log Namespace support to sinks

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#15453]
Sinks need updated to work correctly when the `vector` log namespace is enabled. The only change required is related to the "global log schema". The `vector` namespace no longer uses the "global log schema", so sinks that use this to fetch data need to switch to getting this data from somewhere else. Usually either from "semantic meaning", or from vector metadata.

| Global Log Schema Field | Migrate To |
| --- | ----------- |
| message | semantic meaning ("message") |
| host | semantic meaning ("host") |
| timestamp | semantic meaning ("timestamp"), defaulting to the current time if it doesn't exist and is appropriate |
| source_type | `%vector.source_type` should always exist for messages using the `vector` namespace |

Since these sinks will rely on certain semantic meaning fields, it would useful to also have sink requirements which can enforce that the required meanings are set, and that they are the correct type. This involves creating a `schema::Requirement` object that just lists the semantic meaning name, the type, and whether it is required / optional, and adding it to the input in the `SinkConfig::input` function. These should be fairly straightforward to add to sinks.

Since sink requirements (at least initially) will only be required (for most sinks) when the Vector namespace is used, we should either check the `LogNamespace` when creating the requirements, or potentially only enable sink requirements with the Vector namespace.

For each sink:
1. Migrate all uses of the "Global Log Schema" (except for tests / default config options) to use helper methods that fetch data from either the "Global Log Schema" (Legacy namespace) or from semantic meaning / Vector metadata (Vector namespace).
2. Add sink requirements

### Sinks
- [x] #16482
- [x] #16484
- [x] https://github.com/vectordotdev/vector/pull/15473
- [x] #16502
- [x] #16402
- [x] ~~Humio~~ wraps splunk_hec_logs and only uses `log_schema` in config defaults
- [x] #16539
- [x] #16494
- [x] #16454
- [x] #16435
- [x] #16493
- [x] #16474
- [x] #16549
- [x] #16452
- [x] #16457
- [x] #16430
- [x] #16450
- [x] #16585

### Other Work
- [x] Audit sources / transforms to ensure that semantic meaning for "global log schema" values are correct. These are `message`, `host`, `timestamp` (`source_type` is sometimes used, but can be fetched directly from vector metadata)
- [x] https://github.com/vectordotdev/vector/issues/16683
- [x] https://github.com/vectordotdev/vector/issues/16534
- [x] https://github.com/vectordotdev/vector/issues/16730
- [x] https://github.com/vectordotdev/vector/issues/16732
- [x] Check that any sinks added after this list was created are covered
