### ISSUE TITLE
Support for per-component memory usage metrics 

### ISSUE THREAD

**Issue by arshiyasolei** [vectordotdev/vector#15474]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Provide insights into the memory usage of each Vector component with metrics such as `component_allocated_bytes`, `component_allocated_bytes_total`, and `component_deallocated_bytes_total`. This feature currently only supports `unix` based platforms. 

### Tasks
 
- [X] No-op tracing #14933 
- [X] First version of tracing #14995 
- [X] Improved tracing #15168 
- [X] #15221 
- [X] #15366 
- [X] #15393 
- [X] #15401 
- [X]  #15441 
- [X] Add blog
- [x] Further documentation 

Next steps:

- [ ] Track the lifetimes and memory ownership relations across components. 

Notes:

Tracking allocations by default incurs a ~20% performance penalty on our soak tests.

**Comment by rophy** [comment]
Hi,

I'm trying to use this feature to trace the high memory usage of my vector aggregator.

```bash
> kubectl top pods
NAME        CPU(cores)      MEMORY(bytes)
vector-0    3057m           1296Mi
vector-1    3207m           10550Mi
```

metrics of `vector-1`

promql: 

`sum by (component_id, component_type, host) (vector_component_allocated_bytes{namespace="xxxx",host="vector-1"} /1024/1024)`

```
{component_id="root", host="vector-1"}                  24219.322052001953
{component_id="elasticsearch_fluent", host="vector-1"}  80.29908180236816
{component_id="elasticsearch_kong", host="vector-1"}    0.08845901489257812
{component_id="metrics", host="vector-1"}               1.1389617919921875
{component_id="s_fluent", host="vector-1"}              184.68517303466797
{component_id="s_metrics", host="vector-1"}             0.7748947143554688
{component_id="splunk_dmz", host="vector-1"}            0.08385658264160156
{component_id="t_dmzproxy_1", host="vector-1"}          7.43995475769043
{component_id="t_dmzproxy_2", host="vector-1"}          1.2587699890136719
{component_id="t_fluent_1", host="vector-1"}            55.707115173339844
{component_id="t_fluent_2", host="vector-1"}            0.4162311553955078
{component_id="t_kong_1", host="vector-1"}              0.0861968994140625
{component_id="t_kong_2", host="vector-1"}              0.006488800048828125
{component_id="t_kong_3", host="vector-1"}              0.0064907073974609375
{component_id="t_metrics_1", host="vector-1"}           0.0058841705322265625
{component_id="t_metrics_2", host="vector-1"}           0.19850730895996094

``` 

1. Why does root reported much higher memory usage than kubectl top pods?
2. What could be the reason that root has such high memory usage while all the components are so low?

**Comment by jszwedko** [comment]
> What could be the reason that root has such high memory usage while all the components are so low?

My somewhat glib response would be that `root` is doing all of the allocating :) In practice, sources do actually do most of the allocation of memory.

We had wanted to enhance the tracking to track allocations as ownership moves between components so that, for example, memory allocated by the source that was handed off to a transform would be tracked as being owned by the transform, but we haven't been able to implement that yet.

This comment also reminded me that this issue should be closed since it was just used for tracking the now implemented experimental allocation tracking feature.
