### ISSUE TITLE
Rewrite script wrappers in `vdev` to native code

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#16383]
The following subcommands are present in the `vdev` tool as simple wrappers of existing scripts. They should be converted into native Rust code to avoid portability issues and dependencies on external tools. This list is sorted in a rough approximation of complexity.

* [ ] `release-github.sh`
* [ ] `check-component-docs.sh`
* [ ] `package-msi.sh`
* [ ] `release-push.sh`
* [ ] `release-homebrew.sh`
* [ ] `check-docs.sh`
* [ ] `check-version.rb`
* [ ] `generate-manifests.sh`
* [ ] `package-rpm.sh`
* [ ] `build-docker.sh`
* [ ] `package-deb.sh`
* [ ] `release-commit.rb`
* [ ] `package-archive.sh`
* [ ] `release-s3.sh`
* [ ] `generate-release-cue.rb`
* [ ] `check-events`
* [ ] `generate-component-docs.rb`

Any other scripts present in the `scripts` are also candidates, but since those are not yet run through `vdev`, the above should be the priority.
