### ISSUE TITLE
Register all events with metrics

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#16390]
The epic described in #13691 introduced support for registering events for the purpose of amortizing the cost of emitting metrics. When working through the initial events, no observable performance improvement was observed, which was the initial motivation for the process. Since that point, however, it has been discovered that registered metrics avoid a corner case that may cause metrics to prematurely expire. As such, we should continue the process of conversion to ensure no internal metric is prematurely expired. This epic tracks the process of converting all remaining issues that emit metrics to registered events. At the end of the process, all direct uses of the `counter!`, `gauge!`, and `histogram!` macros from the `metrics` crate should be eliminated.

The following list documents all files which contain direct non-test uses of metric emission. The files in `src/internal_event` will roughly correspond to converting all uses within a single component.

* [ ] `lib/vector-buffers/src/internal_events.rs`
* [ ] `lib/vector-common/src/internal_event/service.rs`
* [ ] `lib/vector-core/src/metrics/mod.rs` (`update_counter` macro)
* [ ] `src/internal_events/aggregate.rs`
* [ ] `src/internal_events/amqp.rs`
* [ ] `src/internal_events/apache_metrics.rs`
* [ ] `src/internal_events/api.rs`
* [ ] `src/internal_events/aws.rs`
* [ ] `src/internal_events/aws_cloudwatch_logs.rs`
* [ ] `src/internal_events/aws_ec2_metadata.rs`
* [ ] `src/internal_events/aws_ecs_metrics.rs`
* [ ] `src/internal_events/aws_kinesis.rs`
* [ ] `src/internal_events/aws_kinesis_firehose.rs`
* [ ] `src/internal_events/aws_sqs.rs`
* [ ] `src/internal_events/batch.rs`
* [ ] `src/internal_events/codecs.rs`
* [ ] `src/internal_events/common.rs`
* [ ] `src/internal_events/conditions.rs`
* [ ] `src/internal_events/datadog_metrics.rs`
* [ ] `src/internal_events/datadog_traces.rs`
* [ ] `src/internal_events/dedup.rs`
* [ ] `src/internal_events/dnstap.rs`
* [ ] `src/internal_events/docker_logs.rs`
* [ ] `src/internal_events/encoding_transcode.rs`
* [ ] `src/internal_events/eventstoredb_metrics.rs`
* [ ] `src/internal_events/exec.rs`
* [ ] `src/internal_events/file.rs`
* [ ] `src/internal_events/file_descriptor.rs`
* [ ] `src/internal_events/fluent.rs`
* [ ] `src/internal_events/gcp_pubsub.rs`
* [ ] `src/internal_events/grpc.rs`
* [ ] `src/internal_events/heartbeat.rs`
* [ ] `src/internal_events/host_metrics.rs`
* [ ] `src/internal_events/http.rs`
* [ ] `src/internal_events/http_client.rs`
* [ ] `src/internal_events/http_client_source.rs`
* [ ] `src/internal_events/influxdb.rs`
* [ ] `src/internal_events/internal_logs.rs`
* [ ] `src/internal_events/internal_metrics.rs`
* [ ] `src/internal_events/journald.rs`
* [ ] `src/internal_events/kafka.rs`
* [ ] `src/internal_events/kubernetes_logs.rs`
* [ ] `src/internal_events/log_to_metric.rs`
* [ ] `src/internal_events/logplex.rs`
* [ ] `src/internal_events/loki.rs`
* [ ] `src/internal_events/lua.rs`
* [ ] `src/internal_events/metric_to_log.rs`
* [ ] `src/internal_events/mongodb_metrics.rs`
* [ ] `src/internal_events/nats.rs`
* [ ] `src/internal_events/nginx_metrics.rs`
* [ ] `src/internal_events/open.rs`
* [ ] `src/internal_events/parser.rs`
* [ ] `src/internal_events/postgresql_metrics.rs`
* [ ] `src/internal_events/process.rs`
* [ ] `src/internal_events/prometheus.rs`
* [ ] `src/internal_events/pulsar.rs`
* [ ] `src/internal_events/redis.rs`
* [ ] `src/internal_events/reduce.rs`
* [ ] `src/internal_events/remap.rs`
* [ ] `src/internal_events/sample.rs`
* [ ] `src/internal_events/sematext_metrics.rs`
* [ ] `src/internal_events/socket.rs`
* [ ] `src/internal_events/splunk_hec.rs`
* [ ] `src/internal_events/statsd_sink.rs`
* [ ] `src/internal_events/tag_cardinality_limit.rs`
* [ ] `src/internal_events/tcp.rs`
* [ ] `src/internal_events/template.rs`
* [ ] `src/internal_events/throttle.rs`
* [ ] `src/internal_events/udp.rs`
* [ ] `src/internal_events/unix.rs`
* [ ] `src/internal_events/websocket.rs`
* [ ] `src/internal_events/windows.rs`
* [ ] `src/internal_telemetry/allocations/mod.rs`
* [ ] `src/utilization.rs`
