### ISSUE TITLE
Ensure that `--watch-config` watches all configuration files for changes

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#17283]
This is a tracking issue for gaps in the files that `--watch-config` misses. Users expect that all files that Vector reads from when loading configuration are watched for updates (enrichment tables, TLS certificates, etc.).

Known issues:

- [ ] https://github.com/vectordotdev/vector/issues/9819
- [ ] https://github.com/vectordotdev/vector/issues/10877
- [ ] https://github.com/vectordotdev/vector/issues/11817

**Comment by gllb** [comment]
Hello, I'm ok to submit a change for this. Only I'd need to make sure on how to do it.

Would it make sense to start the file watcher after having loaded the configuration ? 
After this : https://github.com/vectordotdev/vector/blob/master/src/app.rs#L513-L519 

So some configuration keys (eg. `tls.crt_file` and `tls.key_file`) can be extracted and fed to the watcher within `watcher_conf`

**Comment by pront** [comment]
Hi @gllb and thank you for your interest in this! It makes sense to extract the information you need from a loaded configuration e.g. certs or remap files. We can figure out the tiny details on the PR review but this sounds reasonable.

**Comment by gllb** [comment]
Hi @pront  I just created a PR, I'm pretty new to rust so it might need to improvement, please let me know what do you think.

**Comment by valleedelisle** [comment]
To us, reloading the enrichment tables would be the most important thing. We have it generated dynamically, so having to restart vector every time is a bit painful.

**Comment by jszwedko** [comment]
Reopening since https://github.com/vectordotdev/vector/pull/22386 only covers TLS certificates. This is a tracking issue for all `--watch-config` gaps.

**Comment by pront** [comment]
Good call, I think we can close https://github.com/vectordotdev/vector/issues/10877 now?

**Comment by jszwedko** [comment]
> Good call, I think we can close [#10877](https://github.com/vectordotdev/vector/issues/10877) now?

The implementation only implemented it for the `http` sink. I think we still need to implement it for all other components that support `tls` options 🤔

**Comment by cah-rayan-chehab** [comment]
Hello @gllb , I have been using the 0.45.0 nightly release which already has the changes of #22386 implemented in it.

When vector detects TLS certificate changes, it reloads, but the `http` sink does not pick up the new certificates, sending HTTP events with the certificates that Vector was initially started with.

**Comment by gllb** [comment]
Hello, Ok I have to say that I thought the reloading part was just working pretty much as when it load the configuration at startup. So I only patched the watching file code, not the code where the actual reloads occurs.  
But maybe the reload parts need to be also modified ? any help on the code base would be welcome for this @jszwedko @pront.

**Comment by pront** [comment]
Hello, Based on https://github.com/vectordotdev/vector/pull/22386#issuecomment-2643838063 I thought it was working. I will take another look and update this issue.

**Comment by gllb** [comment]
I think I get it : the RunningTopology run the reload here https://github.com/vectordotdev/vector/blob/master/src/topology/running.rs#L226. But since there is not actual change in the config file, as its a change on a referenced file but its reference remain the same (https://github.com/vectordotdev/vector/blob/master/src/topology/running.rs#L241-L247). So HTTP component buffer is never re-claimed. 
It would mean that for this to work it should reload not only based on a diff, but on something else like a inotify from a referenced file (I have no idea how to implement that on this RunningTopology btw)
Does it make sense ?

**Comment by pront** [comment]
It sounds like you want to do a diff on all watched files and if there's at least one change, then you treat it as a changed piece of the topology.

**Comment by gllb** [comment]
`ConfigDiff` is expecting a vector config file, so it'd fail on a `pem` file, no ? And that means all referenced file in vector config needs to be read and saved to be compared in case of a change event ?
And in case there is a diff it needs to be mapped to the right component, is that feasible ? If so I dont see how

**Comment by pront** [comment]
Hi @gllb, unfortunately I expect to be busy until the next Vector release (Feb 24th). If you have a proposed solution, feel free to follow up with a PR. Otherwise, I will try to find some time to dive into this. Until then, we might have to revert https://github.com/vectordotdev/vector/pull/22386 because the changelog is misleading.

**Comment by pront** [comment]
Thank you @gllb, I will review very soon.
