### ISSUE TITLE
Tracking Issue: Data Volume insights

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#17576]
[RFC](https://github.com/vectordotdev/vector/blob/master/rfcs/2023-05-03-data-volume-metrics.md)

Requirements: 

- [ ] Add the source field to the Event metadata to indicate the source the event has come from.
- [ ] Update the Volume event metrics to take a JsonSize value. Use the compiler to ensure all metrics emitted use this. The EstimatedJsonEncodedSizeOf trait will be updated return a JsonSize.
- [ ] Add the Service meaning. Update any sources that potentially create a service to point the meaning to the relevant field.
- [ ] Introduce an event caching layer that caches registered events based on the tags sent to it.
- [ ] Update the emitted events to accept the new tags - taking the telemetry configuration options into account.
- [ ] There is going to be a hit on performance with these changes. Add benchmarking to help us understand how much the impact will be.
