### ISSUE TITLE
Refactor value insertions for `LogEvent` and `TraceEvent`

### ISSUE THREAD

**Issue by pront** [vectordotdev/vector#18059]
## Action Plan
- [x] Refactor all related calls to use [TargetPath](https://github.com/vectordotdev/vrl/blob/main/src/path/mod.rs#L174).
- [x] Add wrappers that accept `Option`s to avoid code duplication throughout the codebase.
- [ ]  The VRL [string_path feature](https://github.com/vectordotdev/vrl/blob/main/Cargo.toml#L34) (currently on by default) should only be used in tests for convenience. See here how to achieve this: https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2.
- [x] Need to update the VRL version used by Vector for the above.
