### ISSUE TITLE
Make YAML the default format for Vector

### ISSUE THREAD

**Issue by pront** [vectordotdev/vector#18323]
> [!IMPORTANT]<br> We are still supporting TOML and JSON.

Parent ticket to track related work.

```[tasklist]
### Tasks
- [x] Make `yaml` the default choice for example configurations.
- [x] Do a pass over all docs and replace examples using `.toml` with `.yaml`.
- [x] Add a format argument to the `generate` command and generate `yaml` configurations by default.
- [x] Add fallback for `/etc/vector/vector.yaml`.
- [x] Write a highlight for the next release.
- [x] Deprecate defaut location `/etc/vector/vector.toml`
- [x] After Vector 0.35.0 is released, we can remove the special code for handling `/etc/vector/vector.toml`
```
