### ISSUE TITLE
Tracking issue for `RUSTSEC-2023-0052`

### ISSUE THREAD

**Issue by fuchsnj** [vectordotdev/vector#18348]
This was added to the `ignore` section of `deny.toml` since dependencies need to upgrade from `webpki` to `rustls-webpki`

Temporary workaround: https://github.com/vectordotdev/vector/pull/18344

Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0052.html

TODO:
- [x] https://github.com/fussybeaver/bollard/pull/328
- [x] https://github.com/mongodb/mongo-rust-driver/pull/935
- [ ] Upgrade AWS SDK (which depends on an outdated `hyper-rustls` version)
   - The `native-tls` feature was removed, which requires migration: https://awslabs.github.io/smithy-rs/design/transport/connector.html
   - An updated branch was added to our fork of the SDK: https://github.com/vectordotdev/aws-sdk-rust/tree/0.56.x-%23749-fix
