### ISSUE TITLE
Add end to end tests for the Datadog components

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#18533]
Currently we have limited integration testing with the Datadog components in Vector.

Given the common use case of

```
 [DD Agent] -> [Vector] -> [DD backend]
 ```
 
 Vector needs better testing around this components. This issue serves as an epic for adding these tests.

```[tasklist]
### Tasks
- [ ] Add e2e tests for DD Agent -> `datadog_agent` source -> `datadog_logs` sink
- [ ] Add e2e tests for DD Agent -> `datadog_agent` source -> `datadog_metrics` sink
- [ ] Add e2e tests for DD Agent -> `datadog_agent` source -> `datadog_traces` sink
- [ ] Add e2e tests for DD Agent -> `datadog_agent` source -> `datadog_events` sink

```
