### ISSUE TITLE
Vector SMP "Workload Checks"

### ISSUE THREAD

**Issue by pront** [vectordotdev/vector#18555]
```[tasklist]
### Tasks
- [x] Write Github Workflow. Create workflow checks directories for Vector. You can find the Agent checks [here](https://github.com/DataDog/datadog-agent/tree/main/test/workload-checks).
- [x] Add a case. Will probably start with something like [this](https://github.com/vectordotdev/vector/tree/master/regression/cases/http_text_to_http_json).
- [x] Add CI support. You can find the Agent CI example [here](https://github.com/DataDog/datadog-agent/blob/82f4318c5adaeceddd49730b9fdbc7d0c5566420/.gitlab/functional_test/workload_checks.yml#L5-L9).
- [x] Make a [new dashboard](https://app.datadoghq.com/dashboard/wj9-9ds-q49?refresh_mode=sliding&from_ts=1694530255018&to_ts=1695135055018&live=true) for Vector workload checks. See the existing one [here](https://app.datadoghq.com/dashboard/fpz-9x8-cgp/smp-workload-checks?refresh_mode=sliding&tpl_var_status%5B0%5D=nightly&from_ts=1692020386144&to_ts=1694612386144&live=true). The `client_team` filter doesn't work. To simplify things we will make a new dashboard dedicated to Vector.
- [ ] Add more experiments
```
