### ISSUE TITLE
TCP load balancing & failover

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#288]
A common feature across log forwards is the ability to load balance data across a static number of addresses. For example:

```
[sink.out]
  type = "tcp"
  addresses = ["1.1.1.1:9000", "1.1.1.1:90001"]
```

Alternatively, DNS could be used for this when support DNS lookup (https://github.com/timberio/vector/issues/252)

## Requirements

- [ ] Default load balancing strategy is round robbin.
- [ ] Default to a `ttl` of 30 seconds, `ttl` is an option the user can adjust. I think 30 seconds is a good default, especially if TLS is enabled. This will reduce the connection setup overhead. Alternatively, we could leave the connection open and balance over those open connections?
- [ ] As a follow up, I'd like to consider how we'd solve failover. This could be accomplished by setting the `ttl` to 0? (ex: [this image](https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/assets%2F-LR7OsqPORtP86IQxs6E%2F-Lf2F2_ZZFRdGwiFpPg1%2F-Lf2FCbVo_U1MlhuyUMx%2Ffluentd_ha.png?generation=1558053970392763&alt=media)).

## Open questions

1. Does this belong in Vector or is it better solved with DNS or another external system? To me, it seems like a light weight feature that would be useful.
2. Anything else I'm missing.

**Comment by kirillt** [comment]
For me it sounds like it should be abstracted to the topology level (balancing any sink via virtual copy of it), because generally balancing could make sense with HTTP/UDP/whatever. But agree with @lukesteensen's concern about deliverability. With implementing the feature at connection level we can rebalance events from dropped connection to any of living ones.

Probably, possible to implement a trait `BalancerSupport` for sinks with TCP implementation for the start, and later implement it for other sinks.

**Comment by LucioFranco** [comment]
@lukesteensen do you think it would make sense to implement TCP sink based around tower, with an immediate response type? This would allow us to use different middleware that tower provides.

**Comment by lukesteensen** [comment]
I'm not sure how awkward that would be vs just doing a simple round-robin ourselves. I'm sure we could get it working, but I'd want to be sure it's a reasonable match.
