### ISSUE TITLE
Incorporate new Lookup code into VRL and vector 

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#7070]
The work done in #5374 shows that it's possible to dramatically speed up [certain vector workloads](https://github.com/timberio/vector/pull/5374#issuecomment-816314169) and this is something we'd like to achieve. Unfortunately #5374 is a _very large_ pull request and is quite challenging to keep maintained or interrogate, consider that we have also demonstrated that the work done there regresses some workloads to an almost equal degree as the speedup. 

So. We want the `Lookup`/`LookupBuf` concept integrated into VRL and vector but we don't want to harm our users while doing it. This epic supplants #5374 and is complete when that work is achieved, but through gradual iteration. 

Tasks:

- [x] [Implement new / fast lookup code, and replace PathIter with it.](https://github.com/vectordotdev/vector/pull/11611)
- [x] Add support for negative indices
- [x] Move new lookup implementations to `Value`. Some are still in `vector-core::event::util`
- [ ] https://github.com/vectordotdev/vector/issues/13033
- [x] Either add support for coalescing to the new lookup code, or remove support from VRL. (Coalescing was added)
- [x] Replace VRL lookup code with the new lookup code.
- [x] https://github.com/vectordotdev/vector/issues/17935
- [x] https://github.com/vectordotdev/vector/issues/18059
- [x] https://github.com/vectordotdev/vector/issues/18104
