### ISSUE TITLE
Drop Vector WASM support

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8036]
While the WASM experiment was a good one, we've reached the point where we need to more heavily invest in it to make it a first-class Vector feature, or drop it due to the maintenance burden. Its current state works, but is not terribly useful given its performance penalty and lack of documentation and SDKs to make writing plugins easier.

Since we don't envision investing it in in the next 6-12 months, we've made the decision to drop it for now given its low usage and lack of compelling use-cases.

Tasks:
- [x] Mark the guides on the website as not usable anymore (and deindex them from the listing)
- [x] Announce removal in one release
- [x] Drop it in the following release

**Comment by bbigras** [comment]
I use kafka with online game servers' log.

I was thinking of using wasm to parse the lines in the right format and then discard all the useless stuff before shipping the line to kafka.

Is it a good use case or I should just ship everything to kafka and only parse the lines once.

I'm not saying that I want wasm to remain, I'm just wondering why there's a lack of compelling use-cases.

**Comment by JeanMertz** [comment]
Hey @bbigras,

We have several solutions that might fit your need. First, we have a general-purpose [Lua transform](https://vector-backup.netlify.app/docs/reference/configuration/transforms/lua/) that allows you to get the same results as the Wasm transform. It _is_ slower, but it might be fast enough for your use-case.

Second, we have a new _native_ [mapping transform](https://vector-backup.netlify.app/docs/reference/configuration/transforms/remap/) that allows you to remap events to give them the shape you want. You can also use the [filter transform](https://vector-backup.netlify.app/docs/reference/configuration/transforms/filter/) to remove any events that aren't of interest to you.

The Wasm transform sits right between these two solutions: It's general-purpose similar to Lua, and while it's not as fast as our native transforms, it _is_ faster than Lua. However, due to the current implementation, the performance wasn't actually _that_ much better compared to Lua, which is why at this point you are probably better off either using Lua if you need maximum flexibility, or the native remap+filter transforms for maximum speed and a good amount of flexibility.

If there's anything in the Remap transform that is lacking for your specific use-case, let us know (either in a new GitHub Issue, or on Discord), since we're actively developing this transform to be as flexible as possible for as many use-cases as we can come up with.

**Comment by dbcfd** [comment]
For me the biggest hole in remap is the lack of state. This is somewhat handled by reduce, but reduce would need more merge strategies, like being able to do the unique values in an array, or take the newest value seen. For instance, we have an array of protocols, we want to keep the longest array. 

https://github.com/timberio/vector/issues/4258 or something like it before WASM support could be dropped.

**Comment by jszwedko** [comment]
Thanks for the thoughts @dbcfd . Are you currently using the `wasm` transform? I'd be curious to hear more about how.

It does seem likely we'll introduce some sort of state for `remap` (or another transform that leverages VRL). Currently, `lua` can be used for that purpose.

**Comment by suvl** [comment]
I was evaluating as of this morning a way to get data periodically from a source (that might be a file in a git repo or a call to an http endpoint or downloading a file from a bucket then parsing a xlsx) that would then be used to decorate logs wit information, like "what type of client does this log belong to? (alpha, beta, normal)" or "what type of service does this client have? (HFC, FTTH, Mobile)" and all this based on 3 or 4 million records of mac addresses. We were intending to test if this was possible to do on-the-fly directly with vector, via wasm, in a speedy fashion (looking up the mac address on a hashmap being the largest time-consuming task here). I see there's no support for file descriptors or sockets and that you're up to dropping wasm altogether for lack of a great use case. How's this for one?

**Comment by jszwedko** [comment]
Hi @suvl !

Thanks for the additional use case! Enrichment like that is something we've been thinking about recently. We are starting with adding the ability to enrich events from a CSV file, but I think this will expand in the future to cover more cases (like making an HTTP request) and maybe even have an `exec` trapdoor to execute arbitrary code to enrich an event.

Currently Lua can be used for this use, unless I'm misunderstanding. It is actually faster than our current WASM support due to serialization/deserialization during WASM interop.

**Comment by jszwedko** [comment]
This was dropped in 0.17.

**Comment by suiluj** [comment]
I still do not understand how to work with custom protobuf encoded bytes? First I thought WASM is the solution to decode protobuf. Now this seems to be deprecated. What is the solution for protobuf decode?

**Comment by jszwedko** [comment]
Hi @suiluj !

A `protobuf` decoder was recently added in https://github.com/vectordotdev/vector/pull/18019. Would you want to test that out?

**Comment by suiluj** [comment]
Hi @jszwedko 

Ah cool! :) I will try this out in the next few days.

Should I use these config paramters?
- https://deploy-preview-18019--vector-project.netlify.app/docs/reference/configuration/sources/kafka/#decoding.desc_file
- https://deploy-preview-18019--vector-project.netlify.app/docs/reference/configuration/sources/kafka/#decoding.message_type

I did not notice these entries before:
- https://vector.dev/docs/reference/configuration/sources/kafka/#decoding.protobuf

My goal is to process messages from azure event hub via the kafka source.  
zstd uncompress already worked.

Is there a special `decode_proto` transform command available/planned or is this new feature only available via theses config parameters? I found these settings for several sources in the docs.

I will comment on the protobuf decode when i tried it out.

**Comment by jszwedko** [comment]
Great, thanks! For now, we just have the `protobuf` codec, but having this same functionality available in VRL as a function (`decode_protobuf`) would be reasonable and match our other codec support (e.g. `parse_json` as an analogue to the `json` codec). If you would find that useful, would you mind opening a feature request on https://github.com/vectordotdev/vrl ?

**Comment by jszwedko** [comment]
> Should I use these config paramters?
> 
> * https://deploy-preview-18019--vector-project.netlify.app/docs/reference/configuration/sources/kafka/#decoding.desc_file
> * https://deploy-preview-18019--vector-project.netlify.app/docs/reference/configuration/sources/kafka/#decoding.message_type
> 
> I did not notice these entries before:
> 
> * https://vector.dev/docs/reference/configuration/sources/kafka/#decoding.protobuf

Yeah, these options are new as of v0.32.0. Correct, you should use the options you found. Let us know how it works!

**Comment by jszwedko** [comment]
Hi @bbigras ! Can you share how you generated the desc file? There is some discussion in https://github.com/vectordotdev/vector/discussions/18273 that you might find relevant.
