### ISSUE TITLE
Enable a single Vector instance to run multiple, independent pipelines natively

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8216]
Product brief [here](https://docs.google.com/document/d/19L5p-kqvROkygDy9t21nV9EOmxgb_DDbsvoV65ixrk0/edit#).

This issue represents the work we want to do this quarter.

- [x] Separate pipelines per data type (https://github.com/vectordotdev/vector/pull/9733)
- [x] Inter-pipeline “linear” processing mode (https://github.com/vectordotdev/vector/pull/9733)
- [x] Linear pipeline transforms (https://github.com/vectordotdev/vector/pull/9733)
- [x] Optional pipeline ordering (https://github.com/vectordotdev/vector/pull/9733)
- [x] #9992
- [x] #9994
- [ ] Add guides for pipelines feature
- [x] https://github.com/vectordotdev/vector/issues/9990
- [x] https://github.com/vectordotdev/vector/issues/9989
- [x] https://github.com/vectordotdev/vector/issues/9895
- [ ] https://github.com/vectordotdev/vector/issues/9894
- [x] https://github.com/vectordotdev/vector/issues/9993

**Comment by jszwedko** [comment]
Closing since this was just used for scheduling (and this transform was removed).
