### ISSUE TITLE
Release v2 of vector source / sink

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8219]
## Summary

We would like to officially release and announce the gRPC version of the Vector source/sink. This source/sink will become the new default pairing as it behaves better in k8s environments with respect to load balancing.

## Requirements
- [x] Documentation for new implementation exists
- [x] 0.16.0 includes a migration guide for moving from v1 -> v2 of the source / sink (with and without downtime)
- [x] 0.16.0 release highlight for this change exists and describes how and why we've made this change (could also be a blog post if we wanted)

**Comment by jszwedko** [comment]
@JeanMertz noting that a [user in discord](https://discord.com/channels/742820443487993987/861983462910590986/867127280593666058) ran into a silent error using v1 of the vector sink with a v2 vector source. I think it'd be helpful to adjust the v2 source to complain if it receives invalid HTTP requests (which is what I assume was happening here?).
