### ISSUE TITLE
CSV Enrichment

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8288]
## Summary

We would like to allow users to enrich events flowing through the topology using a CSV file that stores metadata.

## Jobs to be done
- [x] Users can lookup a row from a CSV file in VRL by a condition

## Requirements
- [x] A function exists to allow users to lookup a CSV row:
  - [x] By column
  - [x] By a set of columns ANDed together
- [x] Users can use the CSV row to enrich their event

**Comment by jszwedko** [comment]
I think this could possibly dovetail with the work to enable iteration / mapping in Vector. I'm imagining possible allowing for something like:

```
lookup_csv_row("/path/to/file.csv", |row| row.some_key = .some_field)
```

But we could start with something simpler to address the core requirements here.

**Comment by StephenWakely** [comment]
This work was done in #8660
