### ISSUE TITLE
`vector tap` improvements

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8292]
## Summary

We would like to complete the work we've started with `vector tap` to make it a fully-baked feature.

## Requirements
- [x] #6892
- [x] Return trace events from `tap` (https://github.com/vectordotdev/vector/pull/10483)
- [x] #6854
- [x] #7116
- [x] #9467
- [x] #11368
- [x] Add a `vector tap` guide (#11517)
- [x] #11514
- [x] #6898
- [x] #6870
- [x] #8770
- [x] https://github.com/vectordotdev/vector/issues/11500

**Comment by leebenson** [comment]
Feature complete; closing this epic. Excellent work all round @001wwang 🎉
