### ISSUE TITLE
FIPS compliance Epic

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8435]
Issues:
- [ ] https://github.com/vectordotdev/vector/issues/16628 
- [ ] https://github.com/vectordotdev/vector/issues/16535
- [x] https://github.com/vectordotdev/vector/issues/21232
- [ ] https://github.com/vectordotdev/vector/issues/23147
- [ ] https://github.com/vectordotdev/vector/issues/18382

---

Original request:

A couple of users in discord have asked about FIPS compliance with regards to Vector:

* https://discord.com/channels/742820443487993987/746076283074773150/867921107875926048
* https://discord.com/channels/742820443487993987/746076283074773150/801807173486116885

I'm not entirely sure what all would be involved to have Vector be FIPS compliant, but at the least it seems like it'd be compiling using this openssl module: https://www.openssl.org/docs/fips.html (probably optionally)

This appears to be required for running applications in AWS GovCloud.

**Comment by syedriko** [comment]
Hi @jszwedko! Making Vector FIPS compliant would involve using exclusively a FIPS-audited crypto implementation for all crypto needs. On RHEL/CoreOS that's OpenSSL, supplied by the OS, linked to Vector dynamically. ring has not been FIPS-auditied. It appears the most interesting part of this work is going to be not with Vector itself, but with it's (transitive) dependencies. For example, the AWS Rust SDK depends on ring directly. rustls is having a discussion along these lines https://github.com/rustls/rustls/issues/521.
Just for an idea what else depends on ring (that's for the feature set we at OpenShift care about):
```
$ cargo tree -i ring --no-default-features --features ocp-logging
ring v0.16.20
├── aws-config v0.9.0
│   └── vector v0.21.0 (/home/syedriko/rust/vector)
├── aws-sigv4 v0.9.0
│   ├── aws-sig-auth v0.9.0
│   │   ├── aws-sdk-cloudwatchlogs v0.9.0
│   │   │   └── vector v0.21.0 (/home/syedriko/rust/vector)
│   │   ├── aws-sdk-sso v0.9.0
│   │   │   └── aws-config v0.9.0 (*)
│   │   └── aws-sdk-sts v0.9.0
│   │       └── aws-config v0.9.0 (*)
│   └── vector v0.21.0 (/home/syedriko/rust/vector)
├── azure_storage v0.1.0 (https://github.com/Azure/azure-sdk-for-rust.git?rev=3ca5610b959b3b6b77bb88da09f0764b605b01bc#3ca5610b)
│   └── azure_storage_blobs v0.1.0 (https://github.com/Azure/azure-sdk-for-rust.git?rev=3ca5610b959b3b6b77bb88da09f0764b605b01bc#3ca5610b)
│       [dev-dependencies]
│       └── vector v0.21.0 (/home/syedriko/rust/vector)
│   [dev-dependencies]
│   └── vector v0.21.0 (/home/syedriko/rust/vector)
├── rustls v0.19.1
│   ├── bollard v0.11.1
│   │   └── vector v0.21.0 (/home/syedriko/rust/vector)
│   ├── hyper-rustls v0.22.1
│   │   ├── aws-smithy-client v0.39.0
│   │   │   ├── aws-config v0.9.0 (*)
│   │   │   ├── aws-sdk-cloudwatchlogs v0.9.0 (*)
│   │   │   ├── aws-sdk-sso v0.9.0 (*)
│   │   │   ├── aws-sdk-sts v0.9.0 (*)
│   │   │   ├── aws-types v0.9.0
│   │   │   │   ├── aws-config v0.9.0 (*)
│   │   │   │   ├── aws-endpoint v0.9.0
│   │   │   │   │   ├── aws-sdk-cloudwatchlogs v0.9.0 (*)
│   │   │   │   │   ├── aws-sdk-sso v0.9.0 (*)
│   │   │   │   │   └── aws-sdk-sts v0.9.0 (*)
│   │   │   │   ├── aws-http v0.9.0
│   │   │   │   │   ├── aws-config v0.9.0 (*)
│   │   │   │   │   ├── aws-sdk-cloudwatchlogs v0.9.0 (*)
│   │   │   │   │   ├── aws-sdk-sso v0.9.0 (*)
│   │   │   │   │   └── aws-sdk-sts v0.9.0 (*)
│   │   │   │   ├── aws-sdk-cloudwatchlogs v0.9.0 (*)
│   │   │   │   ├── aws-sdk-sso v0.9.0 (*)
│   │   │   │   ├── aws-sdk-sts v0.9.0 (*)
│   │   │   │   ├── aws-sig-auth v0.9.0 (*)
│   │   │   │   └── vector v0.21.0 (/home/syedriko/rust/vector)
│   │   │   └── vector v0.21.0 (/home/syedriko/rust/vector)
│   │   └── bollard v0.11.1 (*)
│   ├── rustls-native-certs v0.5.0
│   │   ├── bollard v0.11.1 (*)
│   │   └── hyper-rustls v0.22.1 (*)
│   └── tokio-rustls v0.22.0
│       └── hyper-rustls v0.22.1 (*)
├── sct v0.6.1
│   ├── ct-logs v0.8.0
│   │   ├── bollard v0.11.1 (*)
│   │   └── hyper-rustls v0.22.1 (*)
│   └── rustls v0.19.1 (*)
└── webpki v0.21.4
    ├── hyper-rustls v0.22.1 (*)
    ├── rustls v0.19.1 (*)
    ├── tokio-rustls v0.22.0 (*)
    └── webpki-roots v0.21.1
        └── bollard v0.11.1 (*)
```

**Comment by jszwedko** [comment]
Notably we added VRL encryption/decryption functions using pure Rust implementations which will likely be impacted by this initiative.

**Comment by pront** [comment]
There was some progress on this but also quite a bit of friction:
* https://github.com/vectordotdev/vector/pull/21504#issuecomment-2599032152
* https://github.com/aws/aws-lc-rs/issues/661
* https://github.com/aws/aws-lc/issues/2129

Fortunately, there's no hard blocker. Someone can resurrect PR #21504

**Comment by hligit** [comment]
Newer version of kube-rs supports aws-lc, with which we can make `ring` optional for FIPS compliant build. Raised https://github.com/vectordotdev/vector/pull/24787 to bump kube-rs.

**Comment by thomasqueirozb** [comment]
#25169 had to explicitly remove FIPS (`aws-lc-rs`) in `reqwest` v0.13 due to unrelated issues. Should be addressed when making a FIPS build

**Comment by aghassemlouei** [comment]
Just leaving a note to mention that a similar need has come up for public sector customers running on Google Cloud Platform (GCP).

**Comment by pront** [comment]
I’ve received a few questions about this recently, so I thought leaving a comment might help future readers.

Given an unknown binary, we probably cannot establish FIPS compliance through functional testing alone. We can inspect which cryptographic libraries it appears to use and test it on a FIPS-enabled system, but a defensible conclusion also requires identifying the exact cryptographic module, how the binary was built, and whether the module is operating in its validated environment and approved mode. If anyone with deeper expertise has additional guidance, please share it.

Knowing the Vector configuration helps significantly because it narrows the assessment to the components and cryptographic paths the deployment can invoke; for example TLS, AWS authentication, or VRL cryptographic functions. Each relevant path can then be mapped to the cryptographic implementation that provides it. That mapping matters because these paths do not share one implementation. Vector's own TLS goes through OpenSSL, but AWS SigV4 request signing and the VRL cryptographic functions use pure-Rust implementations, and some optional components bring in a separate TLS stack. Those are not covered by an OpenSSL FIPS provider configuration.

This means an existing Vector binary could theoretically be used in a FIPS-compliant deployment today, depending on the configuration and compliance boundary. In practice this is difficult to establish. A trivial example is a file-to-file pipeline that performs no cryptographic operations; in that case, FIPS cryptographic requirements may not apply to the configured data path. For configurations using cryptography, every invoked path would need to use an approved validated component. Vector’s OpenSSL FIPS provider configuration can cover OpenSSL-based TLS, but it does not by itself make the whole Vector binary FIPS compliant.
