### ISSUE TITLE
Improve Vector source backpressure handling

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8820]
## Summary

We would like to improve the way that sources propagate back-pressure to senders. Currently, the request based sources (like `http` and `socket`) simply stack up incoming connections and requests, without limit, causing high resource usage in the presence of back-pressure.

Instead, we would like to start shedding load at a certain point.

## Jobs to be done

- [x] https://github.com/vectordotdev/vector/pull/10491
- [ ] #7186 Blocked.
- [x] #6961
- [x] #4455
- [x] Survey sources and document how they respond to back-pressure as well as how we would like them to respond. This could involve user configurable behavior (like max number of connections)
- [x] RFC for dynamic TCP connection limits to satisfy #8596
- [x] https://github.com/vectordotdev/vector/issues/10963

**Comment by fuchsnj** [comment]
Overview of the current state of sources

## Sources that need a change to correctly propagate back-pressure

These are HTTP based sources that should (but don't currently) respond with a 429 during back-pressure
- **AWS Kinesis Firehose**
- **Datadog**
- **HTTP**
- **Heroku Logs**: This service only guarantees “best-effort” delivery of logs. (only keeping the last 1500). This is an HTTP based service, so Vector should respond with an HTTP 429 when under load, but Heroku is likely to lose the data and not retry.
- **Prometheus Remote Write**: Prometheus supports back-off for failures
- **Splunk HEC**


These are TCP based sources that do _not_ correctly handle back-pressure 
- **Fluent**: will open multiple connections
- **Logstash**
- **Socket (TCP mode)**
- **StatsD**
- **Syslog**


## Sources that correctly propagate back-pressure

- **Demo Logs**: This produces data on-demand
- **DNSTap**:  This receives from a single unix-socket, so back-pressure is already correctly applied.
- **Docker Logs**: Each docker container gets a single stream that already has back-pressure properly applied
- **Exec**: Writing to stdout from the exec program seems to block until Vector can read it. This effectively propagates the back-pressure
- **File**: This should be fine as-is. You can have up to `max_read_bytes` * number of files of data in memory in addition to the configured sink buffers and pipeline, but that is already configurable and defaults to a fairly small number (2k bytes).
- **JournalD**: Uses a single stream internally that already handles back-pressure appropriately
- **Kubernetes Logs**
- **Socket (Unix Datagram mode)**: Unlike it's UDP counterpart, this is actually a reliable transport, and will correctly handle back-pressure.
- **Socket (Unix stream)**: Unlike it's TCP counterpart, this is only a single stream, so back-pressure it already correctly handled
- **Stdin**
- **Vector (V1)**: Uses at most 1 concurrent connection per instance. Each connection handles back-pressure correctly.
- **Vector (V2)**: gRPC- this handles back-pressure correctly, slowing down the vector sink

These sources poll on an interval, which is delayed during back-pressure
- **Apache Metrics**
- **AWS ECS Metrics**
- **EventStoreDB Metrics**
- **Host Metrics**
- **Internal Metrics**
- **MongoDB Metrics**
- **NGinx Metrics**
- **Postgresql Metrics**
- **Prometheus Scrape**

Pull-based sources that only fetch data as needed
- **AWS S3**: This currently only supports reading filenames from SQS, which is pull-based and doesn’t need additional back-pressure.
- **AWS SQS**
- **Kafka**
- **NATS**

These sources either shouldn't or can't propagate back-pressure and will drop events
- **Internal Logs**: It would probably be unreasonable to attempt to propagate back-pressure to anything that can generate an internal log, so dropping is the best option here
- **Socket (UDP mode)**

**Comment by jszwedko** [comment]
Closing since this was just used for scheduling and we have tracking issues for the remaining work.
