### ISSUE TITLE
Implement processing arrays of events

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9961]
Ref #9776 RFC #9480 - Processing Arrays of Events

- [x] #10809 
- [x] #10864
- [x] #11063
- [x] #11117
- [x] #11350
- [x] #11588
- [x] Improve the batching behavior in the topology.
- [x] Convert sources that can send arrays of events to send `EventVec`. (mostly done, can enhance as needed)
- [x] Convert task transforms that can easily process arrays of events to consume `EventContainer`. (not aware of transforms that could improve with this)
- [x] Convert sinks that can process arrays of events to consume `EventContainer`. (can think about this in the future)
- [x] #11623
